version: '3.0'
services:
    web_api:
        build: .
        ports: 
            - 5000:5000
        environment: 
            - URI_DB=db
        links: 
            - "db:database"
        depends_on:
            - db
        networks: 
            - postgres-compose-network
    db: 
        image: postgres
        ports: 
            - 5432:5432
        environment: 
            - POSTGRES_PASSWORD=root
        networks: 
            - postgres-compose-network
networks: 
    postgres-compose-network:
        driver: bridge
    web-app-api-network:
        driver: bridge